apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pfa-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/Rayen-Abdellaoui/pfa-helm.git
    targetRevision: HEAD
    path: pfa         # ton dossier contenant le chart
    helm:
      valueFiles:
        - values.yaml # ou un fichier personnalisé si tu veux
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
