apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.service.name }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.service.name }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.name }}:{{.Values.backend.image.tag}}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: MONGODB_URI
              value: {{ .Values.backend.env.MONGODB_URI }}
            - name: API_URI
              value: {{ .Values.backend.env.API_URI }}
          volumeMounts:
            - name: logs-volume
              mountPath: /app/logs
      volumes:
        - name: logs-volume
          emptyDir: {}
