apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.service.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.service.name }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.name }}:{{.Values.frontend.image.tag}}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: VITE_API_URL
              value: {{ .Values.frontend.env.VITE_API_URL }}