apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.auth.username }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.auth.password }}