apiVersion: batch/v1
kind: Job
metadata:
  name: mongorestore-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongorestore
          image: {{ .Values.mongorestore.image }}
          command:
            {{.Values.mongorestore.command }}
          volumeMounts:
            {{.Values.mongorestore.volumeMounts }}
      volumes:
        {{ .Values.mongorestore.volumes}}
