apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.service.name }}
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.service.name }}
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          envFrom:
            - secretRef:
                name: mongo-secret
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.pvc.name }}
