mongodb:
  image: mongo:latest
  port: 27017
  username: admin
  password: adminpass
  pvc:
    name: mongo-pvc
    size: 1Gi
  database: PPP

backend:
  image: 
    name : rayenabd/backend
    tag : 10
  port: 5555
  logsVolume: true
  apiUri: frontend

frontend:
  image: 
    name : rayenabd/frontend
    tag : 10
    port: 80
  nodePort: 30080
  viteApiUrl: http://backend:555

mongorestore:
  enabled: true
  dumpPath: ./dump
  scriptPath: ./restore.sh
