mongodb:
  image: mongo:latest
  port: 27017
  service : 
    name: mongodb
  auth :
    username: admin
    password: adminpass
  replicas: 1
  pvc:
    name: mongo-pvc
    size: 1Gi
  database: PPP

backend:
  image:
    name : rayenabd/backend
    tag: test
  service:
    name: backend
    type: ClusterIP
  port: 5555
  logsVolume: true
  replicas: 1
  env:
    apiUri: frontend
    MONGODB_URI : mongodb://admin:adminpass@mongodb:27017/PPP?authSource=admin

frontend:
  image: 
    name : rayenabd/frontend
    tag: test
  service:
    name: frontend
    type: LoadBalancer
  port: 80
  targetPort: 3000
  nodePort: 30080
  env:
    VITE_API_URL: http://backend:5555
  replicas: 1

mongorestore:
  image: rayenabd/mongo-restore:test
  enabled: true
  dumpPath: ./dump
  scriptPath: ./restore.sh

ingress:
  enabled: false
